### ISSUE TITLE
java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed

### ISSUE THREAD

**Issue by mjfroehlich** [mjfroehlich/Stopwatch_with_Productivity_Timer#1]
Parameter `elapsed` has a default value set in `StopwatchViewState`'s primary constructor. Robolectric unit tests fail with `NullPointerException: Parameter specified as non-null is null` - why is that?

Test output when run from Android Studio:

```
Executing tasks: [:Stopwatch_with_Productivity_Timer-task:testDebugUnitTest, --tests, org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick] in project /Users/martinfroehlich/AndroidStudioProjects/Stopwatch with Productivity Timer


> Task :Stopwatch_with_Productivity_Timer-task:preBuild UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:preDebugBuild UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugAidl NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugRenderscript NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:dataBindingMergeDependencyArtifactsDebug UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:generateDebugResValues UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:generateDebugResources UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:mergeDebugResources UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:dataBindingGenBaseClassesDebug UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:generateDebugBuildConfig UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:checkDebugAarMetadata UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:mapDebugSourceSetPaths UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:extractDeepLinksDebug UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugMainManifest UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugManifest UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugManifestForPackage UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugResources UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugKotlin
> Task :Stopwatch_with_Productivity_Timer-task:javaPreCompileDebug UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugJavaWithJavac UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:preDebugUnitTestBuild UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:javaPreCompileDebugUnitTest UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:mergeDebugShaders UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugShaders NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:generateDebugAssets UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:mergeDebugAssets UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:packageDebugUnitTestForUnitTest UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:generateDebugUnitTestConfig UP-TO-DATE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugJavaRes NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:processDebugUnitTestJavaRes NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:bundleDebugClassesToRuntimeJar
> Task :Stopwatch_with_Productivity_Timer-task:bundleDebugClassesToCompileJar
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugUnitTestKotlin
> Task :Stopwatch_with_Productivity_Timer-task:compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :Stopwatch_with_Productivity_Timer-task:testDebugUnitTest
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=29
resources.arsc in APK '/Users/martinfroehlich/.m2/repository/org/robolectric/android-all-instrumented/10-robolectric-5803371-i3/android-all-instrumented-10-robolectric-5803371-i3.jar' is compressed.
Exception in thread "SDK 29 Main Thread @coroutine#2" java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
	at org.hyperskill.stopwatch.StopwatchViewState.__constructor__(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewState.<init>(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewModel.__constructor__(StopwatchViewModel.kt:19)
	at org.hyperskill.stopwatch.StopwatchViewModel.<init>(StopwatchViewModel.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-0(MainActivity.kt:26)
	at org.hyperskill.stopwatch.MainActivity.access$onCreate$lambda-0(MainActivity.kt:15)
	at org.hyperskill.stopwatch.MainActivity$onCreate$3.invokeSuspend(MainActivity.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at org.hyperskill.stopwatch.MainActivity.onCreate(MainActivity.kt:34)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:286)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity(AbstractUnitTest.kt:78)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity$default(AbstractUnitTest.kt:75)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick(Stage2UnitTest.kt:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineId(2), "coroutine#2":StandaloneCoroutine{Cancelling}@2e0c6535, Dispatchers.Main.immediate]

Exception. Test failed on activity execution with java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
	at org.hyperskill.stopwatch.StopwatchViewState.__constructor__(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewState.<init>(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewModel.__constructor__(StopwatchViewModel.kt:19)
	at org.hyperskill.stopwatch.StopwatchViewModel.<init>(StopwatchViewModel.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-0(MainActivity.kt:26)
	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-1(MainActivity.kt:28)
	at android.view.View.performClick(View.java:7140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.robolectric.shadows.ShadowView$_View_$$Reflector22.performClick(Unknown Source)
	at org.robolectric.shadows.ShadowView.performClick(ShadowView.java:238)
	at android.view.View.performClick(View.java)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.clickAndRun(AbstractUnitTest.kt:155)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:79)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:76)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity(AbstractUnitTest.kt:84)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity$default(AbstractUnitTest.kt:75)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick(Stage2UnitTest.kt:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

java.lang.AssertionError: Exception. Test failed on activity execution with java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
	at org.hyperskill.stopwatch.StopwatchViewState.__constructor__(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewState.<init>(StopwatchViewModel.kt)
	at org.hyperskill.stopwatch.StopwatchViewModel.__constructor__(StopwatchViewModel.kt:19)
	at org.hyperskill.stopwatch.StopwatchViewModel.<init>(StopwatchViewModel.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-0(MainActivity.kt:26)
	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-1(MainActivity.kt:28)
	at android.view.View.performClick(View.java:7140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.robolectric.shadows.ShadowView$_View_$$Reflector22.performClick(Unknown Source)
	at org.robolectric.shadows.ShadowView.performClick(ShadowView.java:238)
	at android.view.View.performClick(View.java)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.clickAndRun(AbstractUnitTest.kt:155)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:79)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:76)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity(AbstractUnitTest.kt:84)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity$default(AbstractUnitTest.kt:75)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick(Stage2UnitTest.kt:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity(AbstractUnitTest.kt:86)
	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity$default(AbstractUnitTest.kt:75)
	at org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick(Stage2UnitTest.kt:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


#educational_plugin FAILED + Exception. Test failed on activity execution with java.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
#educational_pluginjava.lang.NullPointerException: Parameter specified as non-null is null: method org.hyperskill.stopwatch.StopwatchViewState.$$robo$$org_hyperskill_stopwatch_StopwatchViewState$__constructor__, parameter elapsed
#educational_plugin	at org.hyperskill.stopwatch.StopwatchViewState.__constructor__(StopwatchViewModel.kt)
#educational_plugin	at org.hyperskill.stopwatch.StopwatchViewState.<init>(StopwatchViewModel.kt)
#educational_plugin	at org.hyperskill.stopwatch.StopwatchViewModel.__constructor__(StopwatchViewModel.kt:19)
#educational_plugin	at org.hyperskill.stopwatch.StopwatchViewModel.<init>(StopwatchViewModel.kt)
#educational_plugin	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#educational_plugin	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
#educational_plugin	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
#educational_plugin	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
#educational_plugin	at java.base/java.lang.Class.newInstance(Unknown Source)
#educational_plugin	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
#educational_plugin	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
#educational_plugin	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
#educational_plugin	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
#educational_plugin	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
#educational_plugin	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
#educational_plugin	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
#educational_plugin	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-0(MainActivity.kt:26)
#educational_plugin	at org.hyperskill.stopwatch.MainActivity.onCreate$lambda-1(MainActivity.kt:28)
#educational_plugin	at android.view.View.performClick(View.java:7140)
#educational_plugin	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#educational_plugin	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#educational_plugin	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#educational_plugin	at org.robolectric.shadows.ShadowView$_View_$$Reflector22.performClick(Unknown Source)
#educational_plugin	at org.robolectric.shadows.ShadowView.performClick(ShadowView.java:238)
#educational_plugin	at android.view.View.performClick(View.java)
#educational_plugin	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.clickAndRun(AbstractUnitTest.kt:155)
#educational_plugin	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:79)
#educational_plugin	at org.hyperskill.tests.stopwatch.Stage2UnitTest$checkCountOneSecondAfterOneSecondOnStartButtonClick$1.invoke(Stage2UnitTest.kt:76)
#educational_plugin	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity(AbstractUnitTest.kt:84)
#educational_plugin	at org.hyperskill.tests.stopwatch.internals.AbstractUnitTest.testActivity$default(AbstractUnitTest.kt:75)
#educational_plugin	at org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick(Stage2UnitTest.kt:76)
#educational_plugin	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#educational_plugin	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#educational_plugin	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#educational_plugin	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
#educational_plugin	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
#educational_plugin	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
#educational_plugin	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
#educational_plugin	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
#educational_plugin	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
#educational_plugin	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
#educational_plugin	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
#educational_plugin	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
#educational_plugin	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
#educational_plugin	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
#educational_plugin	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
#educational_plugin	at java.base/java.lang.Thread.run(Unknown Source)
org.hyperskill.tests.stopwatch.Stage2UnitTest > checkCountOneSecondAfterOneSecondOnStartButtonClick FAILED
    java.lang.AssertionError at Stage2UnitTest.kt:76
1 test completed, 1 failed
> Task :Stopwatch_with_Productivity_Timer-task:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':Stopwatch_with_Productivity_Timer-task:testDebugUnitTest'.
> There were failing tests. See the report at: file:///Users/martinfroehlich/AndroidStudioProjects/Stopwatch%20with%20Productivity%20Timer/Stopwatch%20with%20Productivity%20Timer/task/build/reports/tests/testDebugUnitTest/index.html
* Try:
> Run with --scan to get full insights.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 9s
25 actionable tasks: 5 executed, 20 up-to-date
07:23:47: Execution finished ':Stopwatch_with_Productivity_Timer-task:testDebugUnitTest --tests "org.hyperskill.tests.stopwatch.Stage2UnitTest.checkCountOneSecondAfterOneSecondOnStartButtonClick"'.
```

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (231.9225.5)
    com.jetbrains.edu (2023.11-2023.1-2235)
    IdeaVIM (2.7.5)
    com.github.copilot (1.4.5.4049)

**Comment by RedJocker** [comment]
I have responded to you on discord, but I don't know if you saw that so I'm repeating here:

I don't think this is related to roboletric.
I think maybe it is related to lifecycle issue.
try doing something like this

```
lifecycleScope.launch {
                      
    repeatOnLifecycle(Lifecycle.State.CREATED) {
          //your code
    }
}
```

**Comment by RedJocker** [comment]
also it is highly unusual to have your viewModel as a local variable to onCreate method. The usual way is to have it as a class property. I don't think this is the source of problem, but I'm not 100% sure either. 
Note that you have at least 3 closures referencing your view model, so you won't be releasing the view model from memory when onCreate is over. I'm saying this because maybe you were thinking it would be more memory efficient this way, but it is not.
